Refactorización inicial
IslasGECI/tablero_front pull request #1
Opened 2019-07-16 19:10 UTC by evaristor

@efren-cabrera: ¿Tienes alguna sugerencia sobre cómo debo refactorizar lo que llevamos?

2019-07-16 20:57 UTC, efren-cabrera requested changes
Aquí va una pequeña tanda de correcciones, aún no termino. Me gustaría que cambiaramos la estructura del repositorio. Una propuesta rápida que se me ocurre ahorita sería algo así

```
├── app.py
├── tablero
│      ├── __init__.py
│      ├── [sumodulo para leer archivo o descargar los datos de una api, tal vez io o data]
│              ├── __ini__.py
│              ├── load_record.py (aquí podrías poner la función get_records)
│      ├── Dashboard.py (Aquí creas una clase que represente al dashboard, esto te conviene para no mandar una lista al front end, mejor un json, si tenemos el objeto es fácil pasarlo a json, tal vez que el constructor acepte la salida de get_records y después se pueda sustituir por otra cosa, sería el equivalente al get_dashboard)
├── templates
│      ├── index.html
├── setup.py
├── .gitignore
```

Creo que es buena práctica siempre dejar una línea en blanco al final del archivo.

2019-07-16 20:57 UTC, efren-cabrera commented on src/tablero.py
> +        es_develop = ((tabla.revision == "develop") | (tabla.revision == "development"))
Esto lo repites en la línea 25

2019-07-16 20:57 UTC, efren-cabrera commented on src/tablero.py
> +        ultimo_renglon = tabla.iloc[-1]
Tal vez aquí sea necesario agregar el comentario de por qué buscas el último registro (el más nuevo)

2019-07-16 20:57 UTC, efren-cabrera commented on src/tablero.py
> +    registro_testmake.timestamp = pd.to_datetime(registro_testmake.timestamp)
¿es necesario transformarlos en fecha?
si están en ISO-8601  estas tres líneas podrían ser una sola

`registro_testmake = pd.read_csv(log_name).sort_values(by="timestamp")`

2019-07-16 20:57 UTC, efren-cabrera commented on src/templates/index.html
> +                    <td>{{registro[0]}}</td>
Las identaciones de este archivo están mal

2019-07-16 22:10 UTC, evaristor commented
Gracias por tu revisión, @efren-cabrera. Hacerlo por tandas me parece una buena idea. Iré incorporando esta primer tanda.

2019-07-16 22:17 UTC, evaristor commented on src/templates/index.html
> +                    <td>{{registro[0]}}</td>
Creo que ya quedó. Le pedí al VS Code que lo formatee.

2019-07-16 22:36 UTC, evaristor commented on src/tablero.py
> +        ultimo_renglon = tabla.iloc[-1]
Agregué un comentario; espero que sea claro

2019-07-16 22:44 UTC, evaristor commented on src/tablero.py
> +        es_develop = ((tabla.revision == "develop") | (tabla.revision == "development"))
Lo regactoricé con una funcioncita de un renglón: `is_develop`

2019-07-16 23:31 UTC, evaristor commented on src/tablero.py
> +    registro_testmake.timestamp = pd.to_datetime(registro_testmake.timestamp)
No sé si es necesario; no sé como _debuggiar_. Necesitaré de tu ayuda...

2019-07-17 00:16 UTC, evaristor commented on src/tablero.py
> +    registro_testmake.timestamp = pd.to_datetime(registro_testmake.timestamp)
Listo.

2019-07-17 00:19 UTC, evaristor commented
@efren-cabrera: Me faltó hacer la clase `Dashboard` pero puedes ir revisando el resto

2019-07-17 00:24 UTC, efren-cabrera requested changes
Aquí te va otra sugerencia

2019-07-17 00:24 UTC, efren-cabrera commented on tablero/Dashboard.py
> +        if not np.any(es_develop):
La línea 25 a la 30  se [arece mucho a la línea 32 a 37 ¿se podría hacer una función para reducir el tamaño de esta función y evitar código repetido?

2019-07-17 00:27 UTC, evaristor commented on tablero/Dashboard.py
> +        if not np.any(es_develop):
Tienes razón. Así lo haré.

2019-07-17 00:27 UTC, efren-cabrera commented on tablero/io/load_record.py
> +        ultimo_renglon = tabla.iloc[-1]
¿Qué opinas si en vez de poner un comentario tan largo haces una función? algo como `get_last_try_status` y en la documentación de la función puede ir este comentario

2019-07-17 00:28 UTC, evaristor commented on tablero/io/load_record.py
> +        ultimo_renglon = tabla.iloc[-1]
OK. Así lo hare.

2019-07-17 23:50 UTC, evaristor commented on tablero/Dashboard.py
> +        if not np.any(es_develop):
Creé la función `is_successful()`

2019-07-18 00:23 UTC, evaristor commented on tablero/io/load_record.py
> +        ultimo_renglon = tabla.iloc[-1]
Creé la función `get_last_record()`

2019-07-18 00:28 UTC, evaristor commented
@efren-cabrera: Ya atendí la segunda tanda de comentarios.
Sólo me falta hacer la clase `Dashboard`.
¿Cómo te imaginas que se vería el comando `render_template("index.html", tablero=get_dashboard())` cuando haya creado la clase `Dashboard`?

2019-07-18 20:18 UTC, efren-cabrera commented on app.py
> +def hello_world():
Cambia el nombre de esta función, tal vez podría ser index o dashboard

2019-07-18 20:19 UTC, efren-cabrera commented
> @efren-cabrera: Ya atendí la segunda tanda de comentarios.
> Sólo me falta hacer la clase `Dashboard`.
> ¿Cómo te imaginas que se vería el comando `render_template("index.html", tablero=get_dashboard())` cuando haya creado la clase `Dashboard`?

@evaristor Tal vez la clase la podemos dejar para después. Podríamos crear dos clases una de `Record` o `Repo` que guarde el nombre del repo, nombre del reporte o resultado, el status de la rama _default_ y el de la rama _develop_.

Yo me imagino que podrías hacer algo como

``` python
class Record:
    def __init__(self, repositorie_name, report_name, status_default, status_develop):
        self.repositorie_name = repositorie_name
        ...

class Dashboard:
    __init__(self, log_name="~/.testmake/testmake.log.csv"):
        self.log_name = log_name
        self.records = self.read_log_file()

    def read_log_file(self) -> List[Records]:
        # Aquí iría la mayoría del código de `get_records`
        ...

    def to_json():
        # Aquí iría el código para generar un archivo json
    ...
```

Y ya en la aplicación podríamos utilizarlo

```python
@app.route('/')
def dashboard():
    dashboard = Dashboard()
    return render_template("index.html", tablero=dashboard.to_json())
```

2019-07-22 18:35 UTC, efren-cabrera commented on app.py
> +def hello_world():
@evaristor Este es el único cambio que queda pendiente para que te la apruebe

2019-07-22 23:46 UTC, efren-cabrera approved these changes

2019-07-23 01:00 UTC, merged