Release test y ci
IslasGECI/tablero_front pull request #16
Opened 2021-06-22 18:24 UTC by nepito

2021-06-23 18:07 UTC, xwalls commented
Esto ya fue revisado en su feature. considero que puede ser aprobada.
que piensas tu @evaristor?

2021-06-23 18:09 UTC, nepito commented
> Esto ya fue revisado en su feature. considero que puede ser aprobada.
> que piensas tu @evaristor?

@xwalls le falta actualizar el _actions_. Ahora ya tenemos unos ejemplos distintos.

2021-06-23 18:10 UTC, evaristor requested changes

2021-06-23 18:10 UTC, evaristor commented on .github/workflows/actions.yml
> +on: [push, pull_request]
```suggestion
on:
  pull_request:
    branches:
      - develop
      - master
  push:
    branches:
      - develop
      - master
```

2021-06-23 18:10 UTC, evaristor commented on .github/workflows/actions.yml
> +      run: docker build --tag tablero_front .
```suggestion
      run: docker build --tag islasgeci .
```

2021-06-23 18:10 UTC, evaristor commented on .github/workflows/actions.yml
> +      run: docker run tablero_front make tests
```suggestion
      run: docker run islasgeci make tests
```

2021-06-23 18:12 UTC, xwalls commented
> @xwalls le falta actualizar el _actions_. Ahora ya tenemos unos ejemplos distintos.

Justo lo que propuso también evaristo. Creo que utilice un ejemplo más viejito cuando agregue el actions.
Va le damos por ahi!

2021-06-23 18:13 UTC, evaristor commented
> Creo que utilice un ejemplo más viejito cuando agregue el actions.

 Tal vez convenga revisar [este PR](https://github.com/IslasGECI/dummy-transformations.py/pull/3).

2021-06-23 22:34 UTC, evaristor commented
> Esto ya fue revisado en su feature.

@xwalls Lo que se revisa en una _feature_ debería ser diferente a lo que se revisa en una _release_. Que algo ya haya sido revisado en una _feature_ no implica que no requiera revisión en la _release_.

2021-06-23 22:50 UTC, xwalls commented
> > Esto ya fue revisado en su feature.
> 
> @xwalls Lo que se revisa en una _feature_ debería ser diferente a lo que se revisa en una _release_. Que algo ya haya sido revisado en una _feature_ no implica que no requiera revisión en la _release_.

Gracias @evaristor!  A veces se me olvida esa diferencia.

2021-06-24 16:36 UTC, xwalls commented on .github/workflows/actions.yml
> +on: [push, pull_request]
aceptaré tus sugerencias!

2021-06-24 16:38 UTC, xwalls commented on .github/workflows/actions.yml
> +      run: docker run tablero_front make tests
corregiré esto en mi local, gracias!

2021-06-24 16:56 UTC, evaristor requested changes
- [ ] Agrega prueba para verificar que la aplicación regresa código de estado 200 en el localhost:5000

2021-06-28 18:59 UTC, evaristor requested changes

2021-06-28 18:59 UTC, evaristor commented on .github/workflows/actions.yml
> +      run: docker run islasgeci/tablero_front make check
```suggestion
      run: make --makefile=build/Makefile check
```

2021-06-28 18:59 UTC, evaristor commented on build/Makefile
> +
```suggestion
check:
	docker run islasgeci/tablero_front make check

```

2021-06-28 19:10 UTC, xwalls commented on .github/workflows/actions.yml
> +      run: docker run islasgeci/tablero_front make check
Gracias evaristo, acepto tu sugerencia!

2021-06-28 19:11 UTC, xwalls commented on build/Makefile
> +
Gracias evaristo, acepto tu sugerencia!

2021-06-28 21:22 UTC, evaristor approved these changes

2021-06-28 21:22 UTC, merged